version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - dotnet restore Backend/RateMyTMUCourses/RateMyTMUCourses.csproj
  build:
    commands:
      - dotnet build Backend/RateMyTMUCourses/RateMyTMUCourses.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ Backend/RateMyTMUCourses/RateMyTMUCourses.csproj
artifacts:
  files:
    - '**/*'
  base-directory: 'app/'
